In [1]:
import numpy as np
a=np.array([0,1,2])
print(a.shape)

(3,)


In [2]:
#Broadcasting
#shape mismatch ho agr do aaray ki broadcasting copy banega or dono ka size equal kar dega...taki operation perform o sake
import numpy as np
a=np.tile(np.arange(0,40,10),(3,1)) #dumy data , shape match , multiple data arrange/repeat/duplicate karne ke liye tile use hoga
print(a)
a=a.T
print(a)

b=np.array([0,1,2])
a+b

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [3]:
import numpy as np
a=np.arange(0,40,10)
a.shape
#to add anew column
a=a[:,np.newaxis] #np.newaxis se shape change hoga  --> shape change kyu karna hai...data set me kam karte waqt agr data input field nhi ho rha hai to hum reshape karte hain...ml model banane me
a.shape

b=np.array([0,1,2])
a+b


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [4]:
import numpy as np
c=np.array([[1,2,3],[4,5,6]])
c.ravel() #ye koi copy creat nhi kar rha hai...sirf view dega ki isne flat kiya hai means 2d ko 1d me convert nhi kiya sirf waisa dikhaya hai
# c.T.ravel() #covert 2d array to 1d array---> return a contiguous flattend array. A 1-D array
c.shape
c
d= c.ravel()
d
print(d.reshape(2,3))
print(d.shape)


[[1 2 3]
 [4 5 6]]
(6,)


In [10]:
c[0,0]=100
d

array([100,   2,   3,   4,   5,   6])

In [14]:
a=np.zeros((2,3))
b=a.T.reshape(3*2) #may also return a copy-->reshape kabhi kabhi copy return karta hai
b[0]=50
a
b

array([50.,  0.,  0.,  0.,  0.,  0.])

In [15]:
#adding a dimension
a=np.array([1,2,3,4,5])
a
a[:, np.newaxis]
a

array([1, 2, 3, 4, 5])

In [16]:
a[:, np.newaxis]
a

array([1, 2, 3, 4, 5])

In [22]:
a=np.arange(4*3*2).reshape(4, 3,2) #reshape use---> jab bhi data fit na ho input mee....to uske liye hum reshape ka use karte hain
a
a[0,2,1]
# a.shape

np.int64(5)

In [21]:
a[0,2,1]

np.int64(5)

In [24]:
#RESIZING
a=np.arange(4)
a.resize((8,)) 
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [25]:
#it must not be refer to somewhere else:
b=a
a.resize((4,)) #resize bhi view create karta hai....copy nhi banata hai
a

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [27]:
#sorting data
a=np.array([[5,4,6],[2,3,2]])
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [28]:
#in place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [ ]:
a=np.array([4,3,2,1])
b=npargsort(a)

a[j]